apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secure-file-share-data
  namespace: secure-file-share
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
